### ISSUE TITLE
Improve patch

### ISSUE THREAD

**Issue by oSumAtrIX** [Indranil012/Dropped-Patches#6]
Heres a better implementation of the Nova patch

https://pastebin.com/dEhQtg1A

**Comment by Indranil012** [comment]
Thanks will try to merge blindly as i don't have any coding knowledge 😅

**Comment by oSumAtrIX** [comment]
The diff is from an older base, small changed sill be necessary only

**Comment by Indranil012** [comment]
Merged 2af8805
