### ISSUE TITLE
Merge Spotify patches from ReVanced repo

### ISSUE THREAD

**Issue by cyberboh** [Indranil012/Dropped-Patches#62]
**Motivations:**

The premium unlock patch is working for me; see my comment here: https://github.com/indrastorms/Dropped-Patches/issues/57#issuecomment-2168111217. However, the premium navbar still appears, which is annoying and irritating. I'd like to request merging Spotify patches from ReVanced (https://revanced.app/patches?pkg=com.spotify.music) into this repo to improve the user experience. Who needs a paid premium navbar if we already have the premium patched?

**Comment by indrastorms** [comment]
You can use both bundle with cli or manager(compose)

**Comment by oSumAtrIX** [comment]
Or patch twice

**Comment by oSumAtrIX** [comment]
That's not the correct approach. Each repo is supposed to ship its own patches. 

The command above is right
